name : CICD Database Development To Production

on:
  push:
    branches:
      - main 

jobs:
  db_cicd: 
    name : Database CICD
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name : SSH Remote Server and Deploy via Git
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: | 
            # Immediately switch to root to avoid home directory permission issues
            sudo -i
            
            echo "Berhasil Terhubung Ke Server"
            
            # Ensure the target directory exists
            mkdir -p /home/cicd/cicd_hehe
            cd /home/cicd/cicd_hehe
            ls  
            echo "Berhasil Masuk Ke Folder CICD Database Exercise"

            
            # Use Git to deploy the code with root privileges
            if [ -d ".git" ]; then
              echo "Git directory exists, pulling latest changes"
              git fetch origin main
              git reset --hard origin/main
              echo "Successfully updated from Git repository"
            else
              echo "Git directory does not exist, cloning repository"
              git clone https://github.com/PliTheGeek/cicd_example .
              echo "Successfully cloned repository"
            fi
            
            # Run Docker compose after the code is updated
            docker compose up -d 
            echo "Berhasil Menjalankan Docker Compose"